"""Structural ports used at CraftControl's replaceable boundaries.

Protocols keep application dependencies explicit without requiring inheritance or a
runtime dependency-injection framework. Concrete adapters satisfy these contracts
structurally.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Protocol


class StateStore(Protocol):
    def initialize(self) -> None: ...
    def snapshot(self, refreshing: bool = False) -> dict[str, Any]: ...
    def store(self, kind: str, values: dict[str, str], source: str) -> None: ...
    def replace(self, kind: str, values: dict[str, str], source: str) -> None: ...
    def reconcile_online_players(self, players: list[str], xuids: dict[str, str], source: str) -> None: ...
    def observe_player(self, name: str, connected: bool, xuid: str = "", source: str = "bedrock-log", occurred_at: float | None = None) -> dict[str, Any]: ...
    def close_online_sessions(self, reason: str, source: str = "docker-events") -> list[str]: ...
    def record_player_death(self, name: str, cause: str, raw: str, source: str, event_key: str) -> bool: ...
    def set_player_permission(self, name: str, permission: str, source: str = "manager") -> None: ...
    def player_profiles(self) -> list[dict[str, Any]]: ...
    def player_profile(self, public_id: str, history_limit: int = 100, session_limit: int = 50) -> dict[str, Any] | None: ...
    def player_activity(self, kind: str, player: str, source: str, search: str, days: int, page: int, page_size: int) -> dict[str, Any]: ...
    def player_rankings(self, limit: int = 10) -> dict[str, Any]: ...
    def block_analytics(self, limit: int = 10) -> dict[str, Any]: ...
    def ingest_telemetry(self, envelope: dict[str, Any]) -> tuple[bool, list[str]]: ...


class PlayerStore(Protocol):
    def snapshot(self, refreshing: bool = False) -> dict[str, Any]: ...
    def store(self, kind: str, values: dict[str, str], source: str) -> None: ...
    def replace(self, kind: str, values: dict[str, str], source: str) -> None: ...
    def observe_player(self, name: str, connected: bool, xuid: str = "", source: str = "bedrock-log", occurred_at: float | None = None) -> dict[str, Any]: ...
    def close_online_sessions(self, reason: str, source: str = "docker-events") -> list[str]: ...
    def record_player_death(self, name: str, cause: str, raw: str, source: str, event_key: str) -> bool: ...
    def set_player_permission(self, name: str, permission: str, source: str = "manager") -> None: ...
    def player_profiles(self) -> list[dict[str, Any]]: ...
    def player_profile(self, public_id: str, history_limit: int = 100, session_limit: int = 50) -> dict[str, Any] | None: ...
    def player_activity(self, kind: str, player: str, source: str, search: str, days: int, page: int, page_size: int) -> dict[str, Any]: ...
    def player_rankings(self, limit: int = 10) -> dict[str, Any]: ...
    def block_analytics(self, limit: int = 10) -> dict[str, Any]: ...


class TelemetryStore(Protocol):
    def snapshot(self, refreshing: bool = False) -> dict[str, Any]: ...
    def store(self, kind: str, values: dict[str, str], source: str) -> None: ...
    def ingest_telemetry(self, envelope: dict[str, Any]) -> tuple[bool, list[str]]: ...


class EventStore(Protocol):
    def record_event(self, topic: str, source: str, payload: dict[str, Any]) -> int: ...
    def events_after(self, event_id: int, limit: int = 100) -> list[dict[str, Any]]: ...


class ServerConfiguration(Protocol):
    @property
    def env_file(self) -> Any: ...
    def read_env(self) -> tuple[list[str], dict[str, str]]: ...
    def read_properties(self) -> dict[str, str]: ...
    def read_permissions(self) -> list[dict[str, Any]]: ...
    def write_env(self, updates: dict[str, str]) -> None: ...


class ServerConsole(Protocol):
    container_name: str
    def query_state(self) -> tuple[dict[str, str], list[str], int, int, dict[str, str]]: ...
    def query_gamerules(self, rules: set[str]) -> dict[str, str]: ...
    def send(self, parts: list[str]) -> None: ...
    def send_and_read(self, parts: list[str]) -> str: ...
    def set_operator(self, player: str, enabled: bool) -> None: ...
    def request_telemetry_snapshot(self) -> str: ...


class ContainerOperations(Protocol):
    def status(self) -> dict[str, Any]: ...
    def execute(self, action: str) -> None: ...


class PublishedEvent(Protocol):
    id: int
    topic: str
    timestamp: float
    source: str
    payload: dict[str, Any]


class EventPublisher(Protocol):
    def publish(self, topic: str, source: str, payload: dict[str, Any] | None = None) -> PublishedEvent: ...
    def stream(self, after_id: int = 0) -> Iterator[PublishedEvent | None]: ...


class RuntimeSupervisor(Protocol):
    def start(self) -> None: ...


class RuntimeApplication(Protocol):
    @property
    def refreshing(self) -> bool: ...
    def refresh_async(self, reason: str = "manual") -> None: ...
    def request_telemetry_snapshot_async(self, reason: str) -> None: ...
    def telemetry_event(self, envelope: dict[str, Any]) -> None: ...
    def player_event(self, player: str, connected: bool, xuid: str = "") -> None: ...
    def player_death_event(self, player: str, cause: str, raw: str) -> bool: ...
    def players(self) -> list[dict[str, Any]]: ...
    def refresh_gamerules_async(self, rules: set[str]) -> None: ...
    def refresh_permissions(self, publish: bool = True) -> None: ...
    def close_online_sessions(self, reason: str) -> list[str]: ...
